### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by CrazyCrud** [Simonwep/candy#6]
Thank you for your work.

I tried a few different URLs but the download doesn't seem to work anymore. I can choose between the options but when I press the download button nothing happens.

I'm on Windows 64.

Thanks in advance!

**Comment by r0bbie** [comment]
Having the same issue when trying on Linux. Click "Download" and get no output at all, nothing appears to happen.

**Comment by simonwep** [comment]
Hey @CrazyCrud  / @r0bbie!

Sorry for the late response, yep. lot's of things were broken and apparently `ytdl-core` released an update. I've published [1.0.3](https://github.com/Simonwep/candy/releases/tag/1.0.3) where these things should be fixed :)

**Comment by CrazyCrud** [comment]
Hey @Simonwep,

no problem and thank you for you response!
Unfortunately, I still get the same error with the new version 1.0.3.
I'll download the source and maybe I can provide you with more information on the problem.

**Comment by simonwep** [comment]
@CrazyCrud Yep, can confirm `1.0.3` is broken. Seems like a major dependence update was responsible for that. I've published [1.0.4](https://github.com/Simonwep/candy/releases/tag/1.0.4) where this should be fixed :)

**Comment by Joshuabump** [comment]
@Simonwep this is happening for me and I'm using 1.0.4

**Comment by Joshuabump** [comment]
in the console, it says **[this](https://i.imgur.com/wMeQRG3.png)** whenever I click download

**Comment by simonwep** [comment]
I've made major changes / updates. Check out the latest [release](https://github.com/Simonwep/candy/releases/tag/1.1.0)!

**Comment by CrazyCrud** [comment]
@Simonwep Thank you for the new release. The download seems to work now.

**Comment by Ampsicora** [comment]
Hey @Simonwep I've got a similar issue on the v1.1.0, when I enter the video link, it starts elaborating and shows the loading icon but then I don't get any results

No results screenshot:
![image](https://user-images.githubusercontent.com/10254145/100379795-cefbff80-3015-11eb-8e6d-eee498403222.png)

**Comment by simonwep** [comment]
@Ampsicora Try the unshorted url, `youtu.be` may not be supported right now.

**Comment by Ampsicora** [comment]
Unfortunately I get the same issue

**Comment by raelb** [comment]
I had the same issue. I recommend to run from source instead of release version, since the `ytdl-core` module is being constantly updated. Follow these steps:

Clone repo
`npm install`

Update ytdl-core to latest version:
`npm install ytdl-core@latest`

Then start the application with
`npm run electron:serve`

**Comment by simonwep** [comment]
@r0bbie @Ampsicora I'll release a new patch version with the updated ytdl-core version later this week!

**Comment by awesomeferret** [comment]
Same issue for me, high CPU and hanging and adding a YouTube link does nothing. Looking forward to the update! :)
